### ISSUE TITLE
Narrative/Texts for MVP

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/commons-simulator#10]
Turn the MVP spec into a narrative doc

**Comment by Jeff-Emmett** [comment]
Dropping the link to Electraseed Funds 'Fractal Ownership' article in the case that it is helpful for a 'solarpunk' style narrative, if that's what Dani decides on:

https://medium.com/freeelio-studios/a-theory-of-fractal-ownership-part-1-introducing-value-based-ownership-54e7edc58953

**Comment by GriffGreen** [comment]
this is the almost done, just need to revise with the illustrator
