### ISSUE TITLE
Readme needs to be reviewed by the Content team

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/commons-simulator#129]

**Comment by Danibelle** [comment]
Hi! So is this issue to update the README file for this Repo?

**Comment by Danibelle** [comment]
It seems like Jeff has put together a great compilation of info for that: https://docs.google.com/document/d/1kKwEKptnvU-mwABF7ORHWlSn6NmYJZfGS7ThTqRqZ3Q/edit?usp=sharing

**Comment by Danibelle** [comment]
And there's the original document.. we can link to these and put a few highlights in a table @laurenluz

**Comment by laurenluz** [comment]
The readme is here: https://github.com/commons-stack/commons-simulator

My only suggestion is that perhaps we get more specific at the bottom where we have the links, changing the text to:

Play the game here!
Read our Medium blog post
Donate to our Gitcoin grant
Join out Telegram Channel
Learn more about the Commons Stack

What do you think @Danibelle ?
