### ISSUE TITLE
Redefine alpha as time to reach 80% of max power

### ISSUE THREAD

**Issue by sembrestels** [commons-stack/commons-simulator#14]
Alpha can be used to derive a sort of [Half-life](https://en.wikipedia.org/wiki/Half-life) for voting power...

This question is asked in our narrative:

G. (Alpha) How many days does it take to reach 80% of a voter’s max voting weight?

2 things

1. We need to confirm that the cadCAD Sim is ready to accept and interpret the user input... 

2. We should decide on a range of days (min and max) min = 5? max = 180?

**Comment by randomshinichi** [comment]
done in 1af3cfdeccf6f27c7ae0fac94d8882c6eda85cb4
