### ISSUE TITLE
Vesting chart in D3

### ISSUE THREAD

**Issue by sembrestels** [commons-stack/commons-simulator#15]
![download](https://user-images.githubusercontent.com/931684/75290076-eeb08e00-581f-11ea-9259-12a5b18ae19f.png)

Implement the following code in a D3 chart:

```python
fig, ax = plt.subplots(figsize=(10,4))
X= np.arange(0,12, .01)
vals = [1-1/2**x for x in X]

vals3 = [1/2**x for x in X]
ax.plot(X,vals, X, vals3)
plt.xlabel('months')
plt.ylabel('percent vested')
plt.title('Vesting Schdule with 1 month vesting "Half-Life"')
plt.legend(["Share of hatch tokens Vested", "Share of Hatch tokens Locked"])
plt.vlines(3,0,1, linestyle ='-.')
plt.text(3.2,.85, str(int(1000*7/8)/10)+ "% of tokens vested after 3 months" )
plt.scatter(3,7/8)
```

Blue line formula is `1-1/2^x` and orange one is `1/2^x`.

Subtasks:
- [ ] Implement chart in D3.
- [ ] Make it interactive: show dashed line and percentage indicator below the mouse.
- [ ] Vesting half-life is parametrized for one month. It should depend on the value we pass to it.

**Comment by GriffGreen** [comment]
The vesting for a Commons is really 2 parameters... we only want the user to give 1...

Specifically we ask the user:

D. (Cliff + Vesting Curve 1/2 life) How many days will pass before 80% of the Hatcher’s tokens are unlocked?

so this number of days needs to be converted into the cliff and half life... We need to determine what a good ratio is and then make it work!

so if we say the ratio is 1/3 cliff and 2/3 half life curve, if they say 6 months... we have a 2 month cliff and a 4 months till 80%... which would mean a 1/2 life of about 55 days-ish

if they say 24 months, there would be an 8 month cliff and 16 months till 80% vesting
