### ISSUE TITLE
Make the "Play again" button consistent

### ISSUE THREAD

**Issue by ghost** [commons-stack/commons-simulator#155]
When hitting the "Play again" button on the final page (the one that shows the simulation's score), the user goes back to the very beginning of the simulation game and has to view again the introductory pages.

When using the link "Analyze your charts again" on the same final page, then hitting the "Play again" button on the page with the funding pool, sentiment, and token price charts, introductory pages are skipped, which saves a lot of time!

The "Play Again" button should have the same behavior in both pages, preferably the one in the chart page.

**Comment by GriffGreen** [comment]
This is a great quick fix! Thx @philh
