### ISSUE TITLE
Cache user progress

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/commons-simulator#25]
the game should only take 8 minutes-ish... but as they move through the game, we should save their progress.

**Comment by GriffGreen** [comment]
should be easy and can be stored in local storage

**Comment by BenSchZA** [comment]
This feeds into what I started on in #1 . I think it might make the most sense to have the Python server set and manage the progress in the existing Flask user sessions. These sessions are stored as cookies, as local storage is accessible client side only.

**Comment by GriffGreen** [comment]
there is debate on if this adds value to the ux... up to debate!

**Comment by BenSchZA** [comment]
:+1: We have user sessions, so storing and fetching progress will be fairly easy (max 2 hours work). As Griff says, up to UX choice.
