### ISSUE TITLE
Mock up for Design

### ISSUE THREAD

**Issue by sembrestels** [commons-stack/commons-simulator#34]
Some wireframes on how to display the story, images, and displays would be really useful before we code it.

---- Griff's Edit----
We need to simply modify this figma:
https://www.figma.com/file/IAbpKrW0SRPUVuWBIxKGVH/Commons-Stack

To make a continuous scroll design for mobile

We need a mock up of every selection tool, what the screens look like with just text and what the screen looks like with a picture and text

All designed for mobile

**Comment by le-dawg** [comment]
Is this issue obsolete now given this figma: https://www.figma.com/proto/cuFTOOajO4aouz4SLnIINz/Commons-Simulator?node-id=557%3A3818&viewport=-1053%2C-94%2C0.0717286691069603&scaling=min-zoom ?

**Comment by markoprljic** [comment]
@GriffGreen This issue can be closed.
