### ISSUE TITLE
Json for the cadCAD Results

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/commons-simulator#36]
We need to figure out the JSONs cadCAD will push out so Phabio can start working on the graphs

**Comment by witwiki** [comment]
I see this is also an old issue now (Apr 15), but I think this one has been done? Unless, I missed something?
Just went through `simrunner.py` under `simulation/` and saw this...

![image](https://user-images.githubusercontent.com/3201174/97767625-237c9e00-1b82-11eb-8332-49141c8c4da6.png)

**Comment by randomshinichi** [comment]
yup it's done now - we need to use github issues better
