### ISSUE TITLE
make game.commonsstack.org display graphs and run simulation

### ISSUE THREAD

**Issue by randomshinichi** [commons-stack/commons-simulator#49]
game.commonsstack.org is the old server backend/web interface to the simulation. Even though it will be superseded by Mr. Black's code in `server/` and Marko's work, it is still useful because it works now and could be used to tune the simulation.

Adapt the code a la `simrunner.py` to make it work.

Graphs needed: time/funding pool, time/token price, time/sentiment

**Comment by santteegt** [comment]
Solved by https://github.com/commons-stack/c-sim-front-end/pull/63
