### ISSUE TITLE
Exit Tribute needs to be more impactful

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/commons-simulator#73]
- [x] A higher Exit Tribute should make the funding pool grow faster and more
- [x] A higher Exit Tribute should make the sentiment of the people who sell go down more
- [x] A higher Exit Tribute should make it more likely for the token price to go down

- [x] Test whether there is a positive correlation between the funding pool and the exit tribute, and as time goes on this correlation should be more dominant.
- [x] Test whether there is an inverse correlation between the token price and the exit tribute. 
- [x] Test whether there is a correlation between the sentiment and the exit tribute.

**Comment by santteegt** [comment]
Wait for a PR on `p_exit_tribute_of_average_speculator_position_size`
