### ISSUE TITLE
Change docker container name to commonssim

### ISSUE THREAD

**Issue by sembrestels** [commons-stack/commons-simulator#8]
We should change the Docker container name to `commonssim` and check that the recent changes to the Dockerfile work.

**Comment by tjayrush** [comment]
The docker build does not work. The README instructs user to 

```
docker build -t commonssim .
docker run -p 5000:5000 commonssim
```

but when I do `docker images` I get

```
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
commonsim                        latest              7307c7b2ee11        7 minutes ago       1.14GB
```
Different name -- there's only one 's' in the image.

**Comment by sembrestels** [comment]
The docker image available at the moment probably is called `cvdemo`. A new image should be created with this repo and a better name, such as `commons-sim` or `commons-simulator`.
