### ISSUE TITLE
Nº of initial proposals should be more impactful on the output graphs!

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/commons-simulator#80]
- [ ] The funding pool should decrease faster at the beggining if there are more initial proposals.
- [ ] The token price is should slightly increase more as time goes on if the nº of initial proposals is higher. 
- [ ] The sentiment should be more likely to go up if there is a high nº of initial proposals

**Comment by marthendalnunes** [comment]
# Initial proposals sensitivity analysis
## Used parameters:
`--hatchers=30 --hatch_tribute=0.4 --timesteps_days=1095 --days_to_80p_of_max_voting_weight=60 --random_seed=42 --max_proposal_request=0.1 --exit_tribute=0.3 `
 

### Sentiment:
![image](https://user-images.githubusercontent.com/18421017/105637922-c45fba00-5e4e-11eb-8dcd-7f6110e9fdd1.png)

### Funding pool:
![image](https://user-images.githubusercontent.com/18421017/105637932-d04b7c00-5e4e-11eb-96ab-c180a1a52915.png)

### Token price:
![image](https://user-images.githubusercontent.com/18421017/105637944-db061100-5e4e-11eb-8e63-5a8bfa561198.png)
