### ISSUE TITLE
Both server and app run, but server crashes when I hit 'run' button on second screen

### ISSUE THREAD

**Issue by tjayrush** [commons-stack/commons-simulator#9]
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  85.04 KB  build/static/js/2.6facceca.chunk.js
  4.58 KB   build/static/js/main.0fefea7c.chunk.js
  787 B     build/static/js/runtime-main.2a32e407.js
  660 B     build/static/css/2.a934fa1a.chunk.css

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

✨  Done in 12.52s.
cp: app/build/static is a directory (not copied).
 * Serving Flask app "server.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "server", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/jrush/Development/commons-simulator/server.py", line 12, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by tjayrush** [comment]
Same problem appears on docker build (which is weird because I thought the problem on the non-docker build was a probably on my machine). I thought the docker build would not exhibit the same problem as my machine, because I thought I understand that this is what docker fixes.

**Comment by sembrestels** [comment]
Should be fixed by https://github.com/commons-stack/commons-simulator/commit/0814247e6965f1ac2d11d3e01da45fb20dd11969. Yaml is not used anymore, but it was still present in the code.
